// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: natsmicro/options.proto

package micro

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Service-level options for NATS microservices
type ServiceOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The NATS subject prefix for all endpoints in this service
	// Optional: defaults to snake_case of service name (e.g., "product_service")
	SubjectPrefix string `protobuf:"bytes,1,opt,name=subject_prefix,json=subjectPrefix,proto3" json:"subject_prefix,omitempty"`
	// Service name (optional, defaults to snake_case of service name)
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Service version (optional, defaults to "1.0.0")
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Service description (optional)
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Service metadata (optional, key-value pairs for service discovery)
	Metadata map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Request timeout (optional, 0 means no timeout)
	// This is the default timeout for all endpoints in this service
	Timeout *durationpb.Duration `protobuf:"bytes,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Skip code generation for this service (optional, defaults to false)
	// Set to true to exclude this service from NATS micro generation
	Skip bool `protobuf:"varint,7,opt,name=skip,proto3" json:"skip,omitempty"`
	// Use JSON encoding instead of binary protobuf (optional, defaults to false)
	// When true, messages are marshaled/unmarshaled using protojson
	// (human-readable) When false (default), messages use binary protobuf
	// encoding (more efficient)
	Json bool `protobuf:"varint,8,opt,name=json,proto3" json:"json,omitempty"`
	// Custom application-specific error codes (e.g., "ORDER_EXPIRED",
	// "PAYMENT_FAILED") These are generated as additional constants,
	// constructors, and checkers alongside the 7 built-in error codes
	// (INVALID_ARGUMENT, NOT_FOUND, etc.)
	ErrorCodes []string `protobuf:"bytes,9,rep,name=error_codes,json=errorCodes,proto3" json:"error_codes,omitempty"`
	// Disable queue subscriptions for this service's grouped endpoints.
	// When true, the generated service registers plain subscriptions instead of
	// queue subscriptions.
	QueueGroupDisabled bool `protobuf:"varint,10,opt,name=queue_group_disabled,json=queueGroupDisabled,proto3" json:"queue_group_disabled,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	mi := &file_natsmicro_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_natsmicro_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOptions.ProtoReflect.Descriptor instead.
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return file_natsmicro_options_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceOptions) GetSubjectPrefix() string {
	if x != nil {
		return x.SubjectPrefix
	}
	return ""
}

func (x *ServiceOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceOptions) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceOptions) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ServiceOptions) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *ServiceOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *ServiceOptions) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

func (x *ServiceOptions) GetErrorCodes() []string {
	if x != nil {
		return x.ErrorCodes
	}
	return nil
}

func (x *ServiceOptions) GetQueueGroupDisabled() bool {
	if x != nil {
		return x.QueueGroupDisabled
	}
	return false
}

// Endpoint-level options for individual RPC methods
type EndpointOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request timeout (optional, 0 means use service default)
	// Overrides the service-level timeout for this specific endpoint
	Timeout *durationpb.Duration `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Skip code generation for this endpoint (optional, defaults to false)
	// Set to true to exclude this specific endpoint from NATS micro generation
	Skip bool `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	// Endpoint metadata (optional, key-value pairs for endpoint-specific
	// metadata) This metadata is passed to the NATS micro endpoint registration
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Disable queue subscriptions for this endpoint.
	QueueGroupDisabled bool `protobuf:"varint,4,opt,name=queue_group_disabled,json=queueGroupDisabled,proto3" json:"queue_group_disabled,omitempty"`
	// Subscription pending message limit for this endpoint.
	// Use -1 for no limit, 0 to keep the library default.
	PendingMsgLimit int32 `protobuf:"varint,5,opt,name=pending_msg_limit,json=pendingMsgLimit,proto3" json:"pending_msg_limit,omitempty"`
	// Subscription pending byte limit for this endpoint.
	// Use -1 for no limit, 0 to keep the library default.
	PendingBytesLimit int32 `protobuf:"varint,6,opt,name=pending_bytes_limit,json=pendingBytesLimit,proto3" json:"pending_bytes_limit,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EndpointOptions) Reset() {
	*x = EndpointOptions{}
	mi := &file_natsmicro_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointOptions) ProtoMessage() {}

func (x *EndpointOptions) ProtoReflect() protoreflect.Message {
	mi := &file_natsmicro_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointOptions.ProtoReflect.Descriptor instead.
func (*EndpointOptions) Descriptor() ([]byte, []int) {
	return file_natsmicro_options_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointOptions) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *EndpointOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *EndpointOptions) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EndpointOptions) GetQueueGroupDisabled() bool {
	if x != nil {
		return x.QueueGroupDisabled
	}
	return false
}

func (x *EndpointOptions) GetPendingMsgLimit() int32 {
	if x != nil {
		return x.PendingMsgLimit
	}
	return 0
}

func (x *EndpointOptions) GetPendingBytesLimit() int32 {
	if x != nil {
		return x.PendingBytesLimit
	}
	return 0
}

// Streaming options for fine-tuning streaming RPC behavior
type StreamOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max concurrent in-flight messages (backpressure, 0 = unlimited)
	MaxInflight int32 `protobuf:"varint,1,opt,name=max_inflight,json=maxInflight,proto3" json:"max_inflight,omitempty"`
	// Guarantee message ordering via sequence headers
	Ordered       bool `protobuf:"varint,2,opt,name=ordered,proto3" json:"ordered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOptions) Reset() {
	*x = StreamOptions{}
	mi := &file_natsmicro_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOptions) ProtoMessage() {}

func (x *StreamOptions) ProtoReflect() protoreflect.Message {
	mi := &file_natsmicro_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOptions.ProtoReflect.Descriptor instead.
func (*StreamOptions) Descriptor() ([]byte, []int) {
	return file_natsmicro_options_proto_rawDescGZIP(), []int{2}
}

func (x *StreamOptions) GetMaxInflight() int32 {
	if x != nil {
		return x.MaxInflight
	}
	return 0
}

func (x *StreamOptions) GetOrdered() bool {
	if x != nil {
		return x.Ordered
	}
	return false
}

// Chunked I/O helpers for simple blob transfer over streaming RPCs.
type ChunkedIOOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the bytes field carrying each payload chunk.
	ChunkField string `protobuf:"bytes,1,opt,name=chunk_field,json=chunkField,proto3" json:"chunk_field,omitempty"`
	// Default chunk size in bytes for generated helpers.
	// When the caller passes 0 to SendReader/SendFile, this value is used.
	// If set to 0 in the proto option itself, defaults to 65536 (64 KB).
	DefaultChunkSize int32 `protobuf:"varint,2,opt,name=default_chunk_size,json=defaultChunkSize,proto3" json:"default_chunk_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChunkedIOOptions) Reset() {
	*x = ChunkedIOOptions{}
	mi := &file_natsmicro_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkedIOOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkedIOOptions) ProtoMessage() {}

func (x *ChunkedIOOptions) ProtoReflect() protoreflect.Message {
	mi := &file_natsmicro_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkedIOOptions.ProtoReflect.Descriptor instead.
func (*ChunkedIOOptions) Descriptor() ([]byte, []int) {
	return file_natsmicro_options_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkedIOOptions) GetChunkField() string {
	if x != nil {
		return x.ChunkField
	}
	return ""
}

func (x *ChunkedIOOptions) GetDefaultChunkSize() int32 {
	if x != nil {
		return x.DefaultChunkSize
	}
	return 0
}

var file_natsmicro_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         50001,
		Name:          "natsmicro.service",
		Tag:           "bytes,50001,opt,name=service",
		Filename:      "natsmicro/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*EndpointOptions)(nil),
		Field:         50002,
		Name:          "natsmicro.endpoint",
		Tag:           "bytes,50002,opt,name=endpoint",
		Filename:      "natsmicro/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*StreamOptions)(nil),
		Field:         50005,
		Name:          "natsmicro.stream",
		Tag:           "bytes,50005,opt,name=stream",
		Filename:      "natsmicro/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*ChunkedIOOptions)(nil),
		Field:         50006,
		Name:          "natsmicro.chunked_io",
		Tag:           "bytes,50006,opt,name=chunked_io",
		Filename:      "natsmicro/options.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional natsmicro.ServiceOptions service = 50001;
	E_Service = &file_natsmicro_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional natsmicro.EndpointOptions endpoint = 50002;
	E_Endpoint = &file_natsmicro_options_proto_extTypes[1]
	// optional natsmicro.StreamOptions stream = 50005;
	E_Stream = &file_natsmicro_options_proto_extTypes[2]
	// optional natsmicro.ChunkedIOOptions chunked_io = 50006;
	E_ChunkedIo = &file_natsmicro_options_proto_extTypes[3]
)

var File_natsmicro_options_proto protoreflect.FileDescriptor

const file_natsmicro_options_proto_rawDesc = "" +
	"\n" +
	"\x17natsmicro/options.proto\x12\tnatsmicro\x1a google/protobuf/descriptor.proto\x1a\x1egoogle/protobuf/duration.proto\"\xb9\x03\n" +
	"\x0eServiceOptions\x12%\n" +
	"\x0esubject_prefix\x18\x01 \x01(\tR\rsubjectPrefix\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12C\n" +
	"\bmetadata\x18\x05 \x03(\v2'.natsmicro.ServiceOptions.MetadataEntryR\bmetadata\x123\n" +
	"\atimeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x12\n" +
	"\x04skip\x18\a \x01(\bR\x04skip\x12\x12\n" +
	"\x04json\x18\b \x01(\bR\x04json\x12\x1f\n" +
	"\verror_codes\x18\t \x03(\tR\n" +
	"errorCodes\x120\n" +
	"\x14queue_group_disabled\x18\n" +
	" \x01(\bR\x12queueGroupDisabled\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x02\n" +
	"\x0fEndpointOptions\x123\n" +
	"\atimeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\bR\x04skip\x12D\n" +
	"\bmetadata\x18\x03 \x03(\v2(.natsmicro.EndpointOptions.MetadataEntryR\bmetadata\x120\n" +
	"\x14queue_group_disabled\x18\x04 \x01(\bR\x12queueGroupDisabled\x12*\n" +
	"\x11pending_msg_limit\x18\x05 \x01(\x05R\x0fpendingMsgLimit\x12.\n" +
	"\x13pending_bytes_limit\x18\x06 \x01(\x05R\x11pendingBytesLimit\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\rStreamOptions\x12!\n" +
	"\fmax_inflight\x18\x01 \x01(\x05R\vmaxInflight\x12\x18\n" +
	"\aordered\x18\x02 \x01(\bR\aordered\"a\n" +
	"\x10ChunkedIOOptions\x12\x1f\n" +
	"\vchunk_field\x18\x01 \x01(\tR\n" +
	"chunkField\x12,\n" +
	"\x12default_chunk_size\x18\x02 \x01(\x05R\x10defaultChunkSize:V\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18ц\x03 \x01(\v2\x19.natsmicro.ServiceOptionsR\aservice:X\n" +
	"\bendpoint\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\v2\x1a.natsmicro.EndpointOptionsR\bendpoint:R\n" +
	"\x06stream\x12\x1e.google.protobuf.MethodOptions\x18Ն\x03 \x01(\v2\x18.natsmicro.StreamOptionsR\x06stream:\\\n" +
	"\n" +
	"chunked_io\x12\x1e.google.protobuf.MethodOptions\x18ֆ\x03 \x01(\v2\x1b.natsmicro.ChunkedIOOptionsR\tchunkedIoB9Z7github.com/franchb/protoc-gen-nats-micro/gen/nats/microb\x06proto3"

var (
	file_natsmicro_options_proto_rawDescOnce sync.Once
	file_natsmicro_options_proto_rawDescData []byte
)

func file_natsmicro_options_proto_rawDescGZIP() []byte {
	file_natsmicro_options_proto_rawDescOnce.Do(func() {
		file_natsmicro_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_natsmicro_options_proto_rawDesc), len(file_natsmicro_options_proto_rawDesc)))
	})
	return file_natsmicro_options_proto_rawDescData
}

var file_natsmicro_options_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_natsmicro_options_proto_goTypes = []any{
	(*ServiceOptions)(nil),              // 0: natsmicro.ServiceOptions
	(*EndpointOptions)(nil),             // 1: natsmicro.EndpointOptions
	(*StreamOptions)(nil),               // 2: natsmicro.StreamOptions
	(*ChunkedIOOptions)(nil),            // 3: natsmicro.ChunkedIOOptions
	nil,                                 // 4: natsmicro.ServiceOptions.MetadataEntry
	nil,                                 // 5: natsmicro.EndpointOptions.MetadataEntry
	(*durationpb.Duration)(nil),         // 6: google.protobuf.Duration
	(*descriptorpb.ServiceOptions)(nil), // 7: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 8: google.protobuf.MethodOptions
}
var file_natsmicro_options_proto_depIdxs = []int32{
	4,  // 0: natsmicro.ServiceOptions.metadata:type_name -> natsmicro.ServiceOptions.MetadataEntry
	6,  // 1: natsmicro.ServiceOptions.timeout:type_name -> google.protobuf.Duration
	6,  // 2: natsmicro.EndpointOptions.timeout:type_name -> google.protobuf.Duration
	5,  // 3: natsmicro.EndpointOptions.metadata:type_name -> natsmicro.EndpointOptions.MetadataEntry
	7,  // 4: natsmicro.service:extendee -> google.protobuf.ServiceOptions
	8,  // 5: natsmicro.endpoint:extendee -> google.protobuf.MethodOptions
	8,  // 6: natsmicro.stream:extendee -> google.protobuf.MethodOptions
	8,  // 7: natsmicro.chunked_io:extendee -> google.protobuf.MethodOptions
	0,  // 8: natsmicro.service:type_name -> natsmicro.ServiceOptions
	1,  // 9: natsmicro.endpoint:type_name -> natsmicro.EndpointOptions
	2,  // 10: natsmicro.stream:type_name -> natsmicro.StreamOptions
	3,  // 11: natsmicro.chunked_io:type_name -> natsmicro.ChunkedIOOptions
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	8,  // [8:12] is the sub-list for extension type_name
	4,  // [4:8] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_natsmicro_options_proto_init() }
func file_natsmicro_options_proto_init() {
	if File_natsmicro_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_natsmicro_options_proto_rawDesc), len(file_natsmicro_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_natsmicro_options_proto_goTypes,
		DependencyIndexes: file_natsmicro_options_proto_depIdxs,
		MessageInfos:      file_natsmicro_options_proto_msgTypes,
		ExtensionInfos:    file_natsmicro_options_proto_extTypes,
	}.Build()
	File_natsmicro_options_proto = out.File
	file_natsmicro_options_proto_goTypes = nil
	file_natsmicro_options_proto_depIdxs = nil
}
