package generator

import (
	"path"

	"google.golang.org/protobuf/compiler/protogen"
)

// PythonLanguage implements Language for Python code generation
type PythonLanguage struct{ BaseLanguage }

// NewPythonLanguage creates a new Python language generator
func NewPythonLanguage() *PythonLanguage {
	return &PythonLanguage{newBaseLanguage("python", "_nats_pb2.py", "templates/python/*.tmpl",
		[]string{"header.py.tmpl"},
		[]string{"shared_header.py.tmpl", "shared.py.tmpl"},
		[]string{"errors.py.tmpl", "service.py.tmpl", "client.py.tmpl"},
	)}
}

// PostGenerate emits a Python __init__.py so the generated directory is a proper package.
func (p *PythonLanguage) PostGenerate(gen *protogen.Plugin, file *protogen.File, pkgDir string) error {
	initFilename := path.Join(pkgDir, "__init__.py")
	initFile := gen.NewGeneratedFile(initFilename, "")
	initFile.P("# Generated by protoc-gen-nats-micro. DO NOT EDIT.")
	return nil
}
